config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about'=>'homes#about' ,as:'about'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update, :index]
  
  patch 'books/:id' => 'books#update', as: 'update_book'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true,length: { minimum: 2, maximum: 200 }
  
  
  # validates :introduction,
    # length: { maximum: 50 }
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
  validates :name, length: { minimum: 2, maximum: 20 },uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  validates :introduction,length: { maximum: 50 }
  
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :is_matching_login_user, only: [:edit, :update]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book=Book.new
  end

 # 投稿データの保存
  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if  @book.save
      flash[:notice] = "You have created book successfully." 
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end
  
  def index
    @books = Book.all
    @book =Book.new
    @user = current_user
  end
  
  def edit
    @books = Book.all
    @book = Book.find(params[:id])
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end
  
 
    
  def update
    @books = Book.all
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully." 
      redirect_to book_path(@book.id) 
    else
      flash.now[:alert]
      render :edit
    end
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.all
    @user = current_user
  end
    
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully." 
      redirect_to user_path(@user.id) 
    else
      flash.now[:alert]
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<div class="col-md-3 mt-3">
  <h2>User info</h2>
  <% if current_user && current_user == @user %>
    <table class="table">
      <tbody>
        <tr></tr>
        <tr>
          <td style="border-top: none;"><%= image_tag current_user.get_profile_image(100, 100) %></td>
        </tr>
        <tr>
          <th>Name</th>
          <td><%= current_user.name %></td>
        </tr>
        <tr>
          <th>Introduction</th>
          <td><%= current_user.introduction %></td>
        </tr>
      </tbody>
    </table>
  <% else %>
    <table class="table">
        <tbody>
          
          <tr>
            <td><%= image_tag user.get_profile_image(100, 100) %></td>
          </tr>
          <tr>
            <th>Name</th>
            <td><%= user.name %></td>
          </tr>
          <tr>
            <th>Introduction</th>
            <td><%= user.introduction %></td>
          </tr>
        </tbody>
    </table>
  <% end %>
  <div class="row">
    
    <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block' do %>
      <i class="fas fa-user-cog"></i> 
    <% end %>
  </div>
  
  <h2 class="mt-2">New book</h2>
  <%= form_with model: Book.new do |f| %>
    <div class='form-group'>
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, autofocus: true, id: "inputTitle", class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :body, "Body" %>
      <%= f.text_area :body, autofocus: true, id: "inputBody", class: 'form-control' %>
    </div>
    <!--<button class="btn btn-success" type="submit">Create Book</button>-->
    <%= f.submit 'Create Book', class: 'btn btn-success'%>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <% if @book.errors.any? %>
        <div class="alert">
          <h4><%= pluralize(@book.errors.count, "error") %>error prohibited this obj from being saved:</h4>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <h2>Editing Book</h2>
      <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
         <div class='form-group'>
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class='form-group'>
          <label for="book_body">Body</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <%= f.submit "Update Book", class: "btn btn-success mb-2" %>
      <% end %>
      <a><%= link_to "Show", book_path(@book) %></a>
      |
      <a><%= link_to "Back", books_path %></a>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class = "container px-5 px-sm-0">
  <div class="row">
    <%= render 'books', user: @user %>
    
    <div class="col-md-8 offset-md-1 mt-3">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
            <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
            <% @books.each do |book| %>
                <tr>
                    <td>
                      <%= link_to user_path(book.user.id) do %>
                        <%= image_tag book.user.get_profile_image(80, 80) %>
                      <% end %>
                    </td>
                    <td> <%= link_to "#{book.title} ", book_path(book.id), class:"text-dark" %></td>
                    <td><%= book.body %></td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class = "container px-5 px-sm-0">
  <div class="row">
    <%= render 'books', user: @user %>
    <div class="col-md-8 offset-md-1 mt-3">
      <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@book.user.id) do %>
                    <%= image_tag @book.user.get_profile_image(80, 80) %>
                  <% end %><br>
                  <%= link_to user_path(@book.user.id) do %>
                    <%= @book.user.name %> <!-- ユーザー名を表示 -->
                  <% end %>
                </td>
                <td> <%= link_to "#{@book.title} ", book_path(@book.id) %></td>
                <td><%= @book.body %></td>
                <% if @book.user == current_user %>
                <td><div class="actions d-flex">
                    <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success custom-button mr-3" %>
                    <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-danger " %>
                </div></td>
                <% end %>
              </tr>
            </tbody>
        </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto">
          Welcome to 
          <i class="fa-solid fa-book"></i>
            <strong>Bookers</strong> !
        </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<div class="col-4 mx-auto mt-5">
  <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!!</h1>
  <p>In  <i class="fa-solid fa-book"></i><strong>Bookers</strong> ,
  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
      <a class="btn btn-info btm-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
    </div>
    <div class="row">
      <a class="btn btn-success btm-sm btn-block mb-3 sign_up" href="/users/sign_up">Sign up</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
        <script src="https://kit.fontawesome.com/b4a254db2e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-dark ">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          
            <a class="navbar-brand text-light" href="/"<span>Bookers</span></a>
          
          
         
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <a class="nav-link text-light" href="<%= user_path(current_user) %>">
                  <i class="fas fa-home" style="color: #ffffff;"></i>Home
                </a>
              </li>
              
              <li>
                <a class="nav-link text-light" href="<%= users_path %>">
                  <i class="fa-solid fa-users" style="color: #ffffff;"></i>Users
                </a>
              </li>

              <%= link_to books_path, class: 'nav-link text-white' do%>
               <i class="fa-solid fa-book-open"></i>Books
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do%>
                <i class="fa-solid fa-sign-out-alt"></i>Log out
              <% end %>
            
            <% else %>
              <li>
                <a class="nav-link text-light" href="<%= root_path %>">
                  <i class="fas fa-home" style="color: #ffffff;"></i>Home
                </a>
              </li>
              
              <li>
                <a class="nav-link text-light" href="<%= about_path %>">
                  <i class="fa-solid fa-link" style="color: #ffffff;"></i>About
                </a>
              </li>
              
              <li>
                <a class="nav-link text-light" href="<%= new_user_registration_path %>">
                  <i class="fa-solid fa-user-plus" style="color: #ffffff;"></i>Sign up
                </a>
              </li>
              
              <li>
                <a class="nav-link text-light" href="<%= new_user_session_path %>">
                  <i class="fas fa-sign-in-alt" style="color: #ffffff;"></i>Log in
                </a>
              </li>
           
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div>
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>">
        <%= value %>
    </div>
  <% end %>
      </div>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div class="alert">
          <h4><%= pluralize(@user.errors.count, "error") %>error prohibited this obj from being saved:</h4>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class='form-group'>
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"user_name",class:'form-control'%>
        </div>
        <div class='form-group'>
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, autofocus: true, id:"user_image",class:'form-control-file'%>
        </div>
        <div class='form-group'>
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, id:"user_introduction",class:'form-control'%>
        </div>
        <div class='form-group'>
          <label for="update_user"></label>
          <%= f.submit :"Update User", autofocus: true, id:"update_user",class:'btn btn-secondary'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/books', user: @user %>
    
    <div class="col-md-8 offset-md-1 mt-3">
      <h2>Users</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(80, 80) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/books', user: @user %>
      <div class="col-md-8 offset-md-1 mt-3">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
            <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
            <% @books.each do |book| %>
                <tr>
                    <td>
                      <%= link_to user_path(book.user.id) do %>
                        <%= image_tag book.user.get_profile_image(80, 80) %>
                      <% end %>
                    </td>
                    <td> <%= link_to "#{book.title} ", book_path(book.id) %></td>
                    <td><%= book.body %></td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
  </div>
</div>